name: puzzle_kids_game
description: A fun puzzle game for kids.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  path_provider: ^2.1.4
  saver_gallery: ^4.0.1
  image: ^4.3.0
  audioplayers: ^6.0.0
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  wakelock_plus: ^1.2.8
  package_info_plus: ^8.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/rewards/
