buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// تزریق ایمن SDK 35 به تمام ماژول‌ها و پلاگین‌ها (جهت جلوگیری از خطای ۳۴ و ۳۵)
subprojects { subproject ->
    subproject.plugins.whenPluginAdded { plugin ->
        if (plugin.class.name.startsWith("com.android.build.gradle")) {
            subproject.android {
                compileSdkVersion 35
                buildToolsVersion "35.0.0"
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
